# CircleCI config that utilises xgo
# Based off:
# https://github.com/billziss-gh/cgofuse/blob/9b5a7c093a2b5da9dc74494e4c7714af8c82de93/.circleci/config.yml
version: 2.1

_defaults: &defaults
    machine: true
    working_directory: ~/.go_workspace/src/github.com/renproject/swapperd
    environment:
      - GOPATH: /home/circleci/.go_workspace


commands:
  dep_ensure:
    description: Installing dependencies
    steps:
      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
              - ~/.go_workspace/src/github.com/renproject/swapperd/vendor
      - run:
          name: Download dependencies
          command: |
            if [ ! -d ~/.go_workspace/src/github.com/renproject/swapperd/vendor ]; then
                if ! [ -x "$(command -v dep)" ]; then
                    mkdir -p ~/.go_workspace/bin
                    curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
                    export PATH=~/.go_workspace/bin:$PATH
                fi
                dep ensure -v
            else
                echo "Dependencies were restored from cache."
            fi
      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
              - ~/.go_workspace/src/github.com/renproject/swapperd/vendor

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Building Docker image
          command: |
            docker build -t karalabe/xgo-latest .
      - dep_ensure
      - run:
          name: Running tests
          command: |
            go test -v ./adapter/...
            go test -v ./core/...
      - run:
          name: Installing xgo
          command: |
            mkdir -p $GOPATH/src
            mkdir -p $GOPATH/bin
            go get -v github.com/karalabe/xgo
      - run:
          name: Build binaries
          command: |
            make
# test:
#   docker:
#     # specify the version
#     - image: circleci/golang:1.9
#   working_directory: ~/.go_workspace/src/github.com/renproject/swapperd
#   steps:
#     - checkout
#     # specify any bash command here prefixed with `run: `
#     - run: go get -v -t -d ./adapter/...
#     - run: go get -v -t -d ./core/...

